// API Schema 导出
export * from "./api/common.js";
export * from "./api/auth.js";
export * from "./api/audit.js";
export * from "./api/captcha.js";
export * from "./api/doctor.js";
export * from "./api/error.js";
export * from "./api/setting.js";
export * from "./api/stats.js";
export * from "./api/system.js";
export * from "./api/user.js";
export * from "./api/post.js";
export * from "./api/tag.js";
export * from "./api/category.js";
export * from "./api/comment.js";
export * from "./api/security.js";
export * from "./api/analytics.js";
export * from "./api/analytics-stats.js";
export * from "./api/page.js";
export * from "./api/storage.js";
export * from "./api/media.js";
export * from "./api/menu.js";
export * from "./api/notice.js";
export * from "./api/message.js";
export * from "./api/search.js";
export * from "./api/project.js";
export * from "./api/friendlink.js";
export * from "./api/recycle-bin.js";
export * from "./api/cron.js";

// 类型安全的 API 客户端工具
export { createApiClient } from "./client.js";
