/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {type: "doc", id: "intro"},
    { type: "autogenerated", dirName: "tutorial-basics" },
    { type: "autogenerated", dirName: "tutorial-extras" },
  ],
  openApiSidebar: [
    {
      type: "category",
      label: "API",
      link: {
        type: "generated-index",
        title: "API 文档",
        description:
          "基于 OpenAPI 规范自动生成的接口文档，涵盖所有可用的 API 端点及其使用方法。",
        slug: "/api"
      },
      items: require("./docs/api/sidebar.js")
    }
  ]
};

export default sidebars;