import type { BlockFormConfig } from "@/blocks/core/types/field-config";

export const SOCIAL_LINKS_BLOCK_FORM_CONFIG: BlockFormConfig = {
  blockType: "social-links",
  displayName: "社交链接区块",
  description:
    "展示社交媒体链接图标，支持 60+ 主流平台。填写 URL 即可显示对应平台图标，多行 Marquee 无限滚动展示。",
  author: {
    name: "RavelloH",
    url: "https://ravelloh.com",
  },
  theme: {
    name: "neutral",
    url: "https://docs.ravelloh.com",
  },
  actions: {
    db: 0,
    config: 0,
  },
  fields: [
    // ===== 基础配置 =====
    {
      label: "顶部标题",
      path: "header",
      type: "text",
      placeholder: "FOLLOW",
      helperText: "顶部标题文本，自动大写",
    },
    {
      label: "底部文本",
      path: "footer",
      type: "text",
      placeholder: "欢迎关注",
    },
    {
      label: "样式",
      path: "layout.style",
      type: "select",
      options: [
        { label: "仅图标", value: "icons-only" },
        { label: "图标+文字", value: "icons-with-text" },
        { label: "仅文字", value: "text-only" },
      ],
      defaultValue: "icons-with-text",
    },
    {
      label: "宽高比",
      path: "layout.ratio",
      type: "number",
      defaultValue: 0.8,
      helperText: "当高度为 1 时，宽度为高度的多少倍",
    },
    {
      label: "滚动行数",
      path: "layout.rows",
      type: "number",
      defaultValue: 2,
      helperText: "Marquee 显示的行数（1-4 行）",
    },
    {
      label: "滚动速度",
      path: "layout.speed",
      type: "number",
      defaultValue: 30,
      helperText: "滚动速度，数值越大越快",
    },

    // ===== 核心社交媒体 =====
    {
      label: "Twitter / X",
      path: "twitter",
      type: "text",
      placeholder: "https://x.com/username",
    },
    {
      label: "Facebook",
      path: "facebook",
      type: "text",
      placeholder: "https://facebook.com/username",
    },
    {
      label: "Instagram",
      path: "instagram",
      type: "text",
      placeholder: "https://instagram.com/username",
    },
    {
      label: "Threads",
      path: "threads",
      type: "text",
      placeholder: "https://threads.net/@username",
    },
    {
      label: "Bluesky",
      path: "bluesky",
      type: "text",
      placeholder: "https://bsky.app/profile/username",
    },
    {
      label: "Mastodon",
      path: "mastodon",
      type: "text",
      placeholder: "https://mastodon.social/@username",
    },
    {
      label: "Fediverse",
      path: "fediverse",
      type: "text",
      placeholder: "https://example.social/@username",
    },
    {
      label: "Friendica",
      path: "friendica",
      type: "text",
      placeholder: "https://friendica.example/@username",
    },

    // ===== 视频平台 =====
    {
      label: "YouTube",
      path: "youtube",
      type: "text",
      placeholder: "https://youtube.com/@channel",
    },
    {
      label: "Bilibili",
      path: "bilibili",
      type: "text",
      placeholder: "https://space.bilibili.com/uid",
    },
    {
      label: "TikTok",
      path: "tiktok",
      type: "text",
      placeholder: "https://tiktok.com/@username",
    },
    {
      label: "Twitch",
      path: "twitch",
      type: "text",
      placeholder: "https://twitch.tv/username",
    },
    {
      label: "Vimeo",
      path: "vimeo",
      type: "text",
      placeholder: "https://vimeo.com/username",
    },
    {
      label: "Kick",
      path: "kick",
      type: "text",
      placeholder: "https://kick.com/username",
    },
    {
      label: "微信视频号",
      path: "wechatChannels",
      type: "text",
      placeholder: "视频号链接",
    },

    // ===== 专业社交 =====
    {
      label: "LinkedIn",
      path: "linkedin",
      type: "text",
      placeholder: "https://linkedin.com/in/username",
    },
    {
      label: "Xing",
      path: "xing",
      type: "text",
      placeholder: "https://xing.com/profile/username",
    },

    // ===== 即时通讯 =====
    {
      label: "Discord",
      path: "discord",
      type: "text",
      placeholder: "https://discord.gg/invite",
      helperText: "Discord 邀请链接或服务器链接",
    },
    {
      label: "Telegram",
      path: "telegram",
      type: "text",
      placeholder: "https://t.me/username",
    },
    {
      label: "WhatsApp",
      path: "whatsapp",
      type: "text",
      placeholder: "https://wa.me/phonenumber",
    },
    {
      label: "Line",
      path: "line",
      type: "text",
      placeholder: "https://line.me/ti/p/@username",
    },
    {
      label: "Messenger",
      path: "messenger",
      type: "text",
      placeholder: "https://m.me/username",
    },
    {
      label: "微信",
      path: "wechat",
      type: "text",
      placeholder: "weixin://...",
      helperText: "微信链接或图片 URL（用于展示二维码）",
    },
    {
      label: "QQ",
      path: "qq",
      type: "text",
      placeholder: "https://qm.qq.com/...",
      helperText: "QQ 群或个人链接",
    },
    {
      label: "KakaoTalk",
      path: "kakaoTalk",
      type: "text",
      placeholder: "https://open.kakao.com/...",
    },
    {
      label: "Skype",
      path: "skype",
      type: "text",
      placeholder: "skype:username?chat",
    },
    {
      label: "Slack",
      path: "slack",
      type: "text",
      placeholder: "https://workspace.slack.com",
    },

    // ===== 开发者平台 =====
    {
      label: "GitHub",
      path: "github",
      type: "text",
      placeholder: "https://github.com/username",
    },
    {
      label: "Gitee",
      path: "gitee",
      type: "text",
      placeholder: "https://gitee.com/username",
    },
    {
      label: "GitLab",
      path: "gitlab",
      type: "text",
      placeholder: "https://gitlab.com/username",
    },
    {
      label: "CodePen",
      path: "codepen",
      type: "text",
      placeholder: "https://codepen.io/username",
    },
    {
      label: "Stack Overflow",
      path: "stackOverflow",
      type: "text",
      placeholder: "https://stackoverflow.com/users/id",
    },
    {
      label: "npm",
      path: "npmjs",
      type: "text",
      placeholder: "https://npmjs.com/~username",
    },
    {
      label: "Vercel",
      path: "vercel",
      type: "text",
      placeholder: "https://vercel.com/username",
    },
    {
      label: "StackShare",
      path: "stackshare",
      type: "text",
      placeholder: "https://stackshare.io/username",
    },

    // ===== 内容/博客平台 =====
    {
      label: "Medium",
      path: "medium",
      type: "text",
      placeholder: "https://medium.com/@username",
    },
    {
      label: "Tumblr",
      path: "tumblr",
      type: "text",
      placeholder: "https://username.tumblr.com",
    },
    {
      label: "知乎",
      path: "zhihu",
      type: "text",
      placeholder: "https://zhihu.com/people/username",
    },
    {
      label: "豆瓣",
      path: "douban",
      type: "text",
      placeholder: "https://douban.com/people/username",
    },
    {
      label: "微博",
      path: "weibo",
      type: "text",
      placeholder: "https://weibo.com/username",
    },
    {
      label: "Blogger",
      path: "blogger",
      type: "text",
      placeholder: "https://username.blogspot.com",
    },
    {
      label: "WordPress",
      path: "wordpress",
      type: "text",
      placeholder: "https://username.wordpress.com",
    },
    {
      label: "Notion",
      path: "notion",
      type: "text",
      placeholder: "https://notion.so/username",
    },
    {
      label: "语雀",
      path: "yuque",
      type: "text",
      placeholder: "https://yuque.com/username",
    },
    {
      label: "GitBook",
      path: "gitbook",
      type: "text",
      placeholder: "https://username.gitbook.io",
    },
    {
      label: "Disqus",
      path: "disqus",
      type: "text",
      placeholder: "https://disqus.com/by/username",
    },

    // ===== 设计平台 =====
    {
      label: "Dribbble",
      path: "dribbble",
      type: "text",
      placeholder: "https://dribbble.com/username",
    },
    {
      label: "Behance",
      path: "behance",
      type: "text",
      placeholder: "https://behance.net/username",
    },
    {
      label: "站酷 ZCOOL",
      path: "zcool",
      type: "text",
      placeholder: "https://zcool.com.cn/u/username",
    },
    {
      label: "Figma",
      path: "figma",
      type: "text",
      placeholder: "https://figma.com/@username",
    },

    // ===== 音乐平台 =====
    {
      label: "Spotify",
      path: "spotify",
      type: "text",
      placeholder: "https://open.spotify.com/user/username",
    },
    {
      label: "SoundCloud",
      path: "soundcloud",
      type: "text",
      placeholder: "https://soundcloud.com/username",
    },
    {
      label: "网易云音乐",
      path: "neteaseMusic",
      type: "text",
      placeholder: "https://music.163.com/#/user/home?id=xxx",
    },

    // ===== 图片分享 =====
    {
      label: "Pinterest",
      path: "pinterest",
      type: "text",
      placeholder: "https://pinterest.com/username",
    },
    {
      label: "Flickr",
      path: "flickr",
      type: "text",
      placeholder: "https://flickr.com/photos/username",
    },
    {
      label: "Unsplash",
      path: "unsplash",
      type: "text",
      placeholder: "https://unsplash.com/@username",
    },
    {
      label: "Pixelfed",
      path: "pixelfed",
      type: "text",
      placeholder: "https://pixelfed.social/username",
    },

    // ===== 自由职业平台 =====
    {
      label: "Fiverr",
      path: "fiverr",
      type: "text",
      placeholder: "https://fiverr.com/username",
    },
    {
      label: "Upwork",
      path: "upwork",
      type: "text",
      placeholder: "https://upwork.com/freelancers/username",
    },

    // ===== 游戏平台 =====
    {
      label: "Steam",
      path: "steam",
      type: "text",
      placeholder: "https://steamcommunity.com/id/username",
    },
    {
      label: "Xbox",
      path: "xbox",
      type: "text",
      placeholder: "https://xbox.com/profile/gamertag",
    },
    {
      label: "PlayStation",
      path: "playstation",
      type: "text",
      placeholder: "https://psnprofiles.com/username",
    },
    {
      label: "Nintendo Switch",
      path: "switchNintendo",
      type: "text",
      placeholder: "SW-XXXX-XXXX-XXXX",
      helperText: "任天堂好友码",
    },

    // ===== 协作工具 =====
    {
      label: "Trello",
      path: "trello",
      type: "text",
      placeholder: "https://trello.com/username",
    },
    {
      label: "Dropbox",
      path: "dropbox",
      type: "text",
      placeholder: "https://dropbox.com/...",
    },
    {
      label: "Spectrum",
      path: "spectrum",
      type: "text",
      placeholder: "https://spectrum.chat/username",
    },

    // ===== 其他平台 =====
    {
      label: "Reddit",
      path: "reddit",
      type: "text",
      placeholder: "https://reddit.com/user/username",
    },
    {
      label: "Snapchat",
      path: "snapchat",
      type: "text",
      placeholder: "https://snapchat.com/add/username",
    },
    {
      label: "VK",
      path: "vk",
      type: "text",
      placeholder: "https://vk.com/username",
    },
    {
      label: "Patreon",
      path: "patreon",
      type: "text",
      placeholder: "https://patreon.com/username",
    },
    {
      label: "Product Hunt",
      path: "productHunt",
      type: "text",
      placeholder: "https://producthunt.com/@username",
    },

    // ===== 通用 =====
    {
      label: "Email",
      path: "email",
      type: "text",
      placeholder: "mailto:hello@example.com",
      helperText: "邮箱链接，以 mailto: 开头",
    },
    {
      label: "RSS",
      path: "rss",
      type: "text",
      placeholder: "https://example.com/rss.xml",
    },
    {
      label: "个人网站",
      path: "website",
      type: "text",
      placeholder: "https://example.com",
    },
  ],
  groups: [
    {
      title: "基础配置",
      description: "设置标题、文本和布局样式",
      fields: [
        "header",
        "footer",
        "layout.style",
        "layout.ratio",
        "layout.rows",
        "layout.speed",
      ],
    },
    {
      title: "核心社交媒体",
      description: "主流社交平台",
      fields: [
        "twitter",
        "facebook",
        "instagram",
        "threads",
        "bluesky",
        "mastodon",
        "fediverse",
        "friendica",
      ],
    },
    {
      title: "视频平台",
      description: "视频内容分享平台",
      fields: [
        "youtube",
        "bilibili",
        "tiktok",
        "twitch",
        "vimeo",
        "kick",
        "wechatChannels",
      ],
    },
    {
      title: "专业社交",
      description: "职业社交网络",
      fields: ["linkedin", "xing"],
    },
    {
      title: "即时通讯",
      description: "聊天和通讯应用",
      fields: [
        "discord",
        "telegram",
        "whatsapp",
        "line",
        "messenger",
        "wechat",
        "qq",
        "kakaoTalk",
        "skype",
        "slack",
      ],
    },
    {
      title: "开发者平台",
      description: "代码托管和开发者社区",
      fields: [
        "github",
        "gitee",
        "gitlab",
        "codepen",
        "stackOverflow",
        "npmjs",
        "vercel",
        "stackshare",
      ],
    },
    {
      title: "内容/博客",
      description: "文章和博客平台",
      fields: [
        "medium",
        "tumblr",
        "zhihu",
        "douban",
        "weibo",
        "blogger",
        "wordpress",
        "notion",
        "yuque",
        "gitbook",
        "disqus",
      ],
    },
    {
      title: "设计平台",
      description: "设计作品分享",
      fields: ["dribbble", "behance", "zcool", "figma"],
    },
    {
      title: "音乐平台",
      description: "音乐分享和流媒体",
      fields: ["spotify", "soundcloud", "neteaseMusic"],
    },
    {
      title: "图片分享",
      description: "图片和摄影平台",
      fields: ["pinterest", "flickr", "unsplash", "pixelfed"],
    },
    {
      title: "自由职业",
      description: "自由职业服务平台",
      fields: ["fiverr", "upwork"],
    },
    {
      title: "游戏平台",
      description: "游戏社区和玩家主页",
      fields: ["steam", "xbox", "playstation", "switchNintendo"],
    },
    {
      title: "协作工具",
      description: "团队协作和项目管理",
      fields: ["trello", "dropbox", "spectrum"],
    },
    {
      title: "其他平台",
      description: "其他社交和内容平台",
      fields: ["reddit", "snapchat", "vk", "patreon", "productHunt"],
    },
    {
      title: "通用链接",
      description: "邮箱、RSS 和个人网站",
      fields: ["email", "rss", "website"],
    },
  ],
  previewData: {
    twitter: "#",
    facebook: "#",
    instagram: "#",
    layout: {
      rows: 4,
      ratio: 1,
    },
    threads: "#",
    bluesky: "#",
    mastodon: "#",
    fediverse: "#",
    friendica: "#",
    youtube: "#",
    bilibili: "#",
    tiktok: "#",
    twitch: "#",
    vimeo: "#",
    kick: "#",
    wechatChannels: "#",
    linkedin: "#",
    xing: "#",
    discord: "#",
    telegram: "#",
    whatsapp: "#",
    line: "#",
    messenger: "#",
    wechat: "#",
    qq: "#",
    kakaoTalk: "#",
    skype: "#",
    slack: "#",
    github: "#",
    gitee: "#",
    gitlab: "#",
    codepen: "#",
    stackOverflow: "#",
    npmjs: "#",
    vercel: "#",
    stackshare: "#",
    medium: "#",
    tumblr: "#",
    zhihu: "#",
    douban: "#",
    weibo: "#",
    blogger: "#",
    wordpress: "#",
    notion: "#",
    yuque: "#",
    gitbook: "#",
    disqus: "#",
    dribbble: "#",
    behance: "#",
    zcool: "#",
    figma: "#",
    spotify: "#",
    soundcloud: "#",
    neteaseMusic: "#",
    pinterest: "#",
    flickr: "#",
    unsplash: "#",
    pixelfed: "#",
    fiverr: "#",
    upwork: "#",
    steam: "#",
    xbox: "#",
    playstation: "#",
    switchNintendo: "#",
    trello: "#",
    dropbox: "#",
    spectrum: "#",
    reddit: "#",
    snapchat: "#",
    vk: "#",
    patreon: "#",
    productHunt: "#",
    email: "#",
    rss: "#",
    website: "#",
  },
};
